### ISSUE TITLE
When search string for name includes comma everything before the comma is ignored.

### ISSUE THREAD

**Issue by rudgutter** [kyleconroy/deckbrew#25]
Hi!

I noticed this yesterday. Before, querying name for "Chandra, fl" would return only the card "Chandra, Flamecaller", but now it ignores everything before the comma in the search string. The query now only returns cards beginning with "fl".

Example: http://api.deckbrew.com/mtg/cards?name=chandra,%20fl

**Comment by kyleconroy** [comment]
This has now been fixed https://github.com/kyleconroy/deckbrew/commit/737f01bc1f7c5e4d3d9c52125b7c83a9d83d24e9. Thanks for the bug report.
