### ISSUE TITLE
Prices are all 0

### ISSUE THREAD

**Issue by Lucent-Sable** [kyleconroy/deckbrew#27]
Recently TCG Player have changed the way they are presenting prices, and it seem that this has affected your API, as all prices are showing as 0.

https://api.deckbrew.com/mtg/cards/tarmogoyf
Is showing
      "price": {
        "low": 0,
        "median": 0,
        "high": 0
      },

**Comment by kyleconroy** [comment]
Sadly, TCGPlayer cut off my access to their prices, hence the zeros. I'd love to add the prices back, but I need another source.
