### ISSUE TITLE
Zendikar Expedition(s) Title Mismatch

### ISSUE THREAD

**Issue by amayer5125** [kyleconroy/deckbrew#29]
When you get the set the name is Zendikar Expedition but when you get a card the set name is Zendikar Expeditions. I believe they should both be Zendikar Expeditions (with the "s").
Example:
https://api.deckbrew.com/mtg/sets/EXP (no "s" at the end)
https://api.deckbrew.com/mtg/cards/canopy-vista (has "s" at the end)

**Comment by kyleconroy** [comment]
Fixed!
