### ISSUE TITLE
Pricing disappeared?

### ISSUE THREAD

**Issue by mplacona** [kyleconroy/deckbrew#31]
Hey looking at your [reddit thread](https://www.reddit.com/r/mtgfinance/comments/1xqp1x/open_source_magic_api_with_pricing_information/) it seems that at some point you had prices in this API.

Have they disappeared? Any chance they're coming back?

Thanks for the great work on this API nonetheless.

**Comment by mplacona** [comment]
Sorry, I should have searched first. Seems like this was already discussed in #27.

Hoping you get access back

**Comment by kyleconroy** [comment]
Marcos, it's unlikely that prices will be coming back. I'd suggest using
ScryFall instead. TCG Player is somehow okay with them using their prices.

**Comment by mplacona** [comment]
Ah thanks man! I somehow could not find scryFall when I google for MTG APIs.

really appreciate you replying to this.

Cheers
